from scipy.spatial.distance import hamming
import Levenshtein as lev
# Determine guide seqs + pam mutations from donors
gen_code = {"A": "T", "T": "A", "G": "C", "C": "G", "N": "N", "X": "X", "c": "g", "g": "c",
            "a": "t", "t": "a", "n": "n"}


def rev_complement(read):
    """
    Creates the reverse complement of a sequence
    Args:
        read: a string, a DNA sequence

    Returns:
        rev_comp_read: a string, the reverse complement of read
    """
    comp_read = ""
    for position in read:
        new_base = gen_code[position]
        comp_read = comp_read + new_base
    rev_comp_read = comp_read[::-1]
    return rev_comp_read


antat_seq = "AACGCTATTATTAGAACAGTTTCTGTACTATATTGAAACAGAAGCCAAAGAGGGAGAGCCACTCATTTCCACCCCTAATACTGGCAATGGTCACCAAGGAGCGAAACGCAGCATTAAAAATTGTAATGTTAGTCGCTTCAGCACTGACACTACACCCACAACAAGCTCTAGCTCAGACCGCTGGTAGGCCCCTTGCAGATGTGGTAGCCAAAACTCTATGTACTTATTCAAAAACGGCCAAACGCCAGGCAGCAAACCTGGCGCAAACACTACAACGAGCCAGCTCAGCAGCAAAGCAATCCAGACAAGCGCAGCAGTTAGCGGCTTTAGCACTGGCCAAACTGCCAGACTACAAAGAAGCAGCCGCGACACTGTTAATTTACGCCACGCACAAAATACAAGACGCGCAAGCCAGCATCGAAAACTGGACAGGAGAGAATACTAAGCTAGTTGGCCAGGCGATGTATTCCTCAGGGAGAATCGACGAACTGATGTTGCTACTAGAAGGGCACCGAGAGGACGGCGCGAACGGACAGGACAAAACTTGCCTAGGCGCGGCCGCCGGCGGCAATACAGTAAATGAATTCGTCAAAACAGAATGCGACACGGAAAGCGGCCACAACATCGAGGCAGACAACTCAAACATAGGGCAAGCGGCAACGACTCTAAGCCAAGAAAGTACAGACCCAGAAGCCAGCGGAGGCGCAAGCTGCAAAATAACAGCAAACCTTGCCACTGACTACGACAGCCATGCGAATGAGTTACCGCTACTCGGCGGCCTGCTAACCATACACAACGCAGGCGGCTTCAAAACAGGACAAAGCTTGCAAACCGCAGCACCAACCAACAAGCTAATCAGCGCACTCAAAAATAAGGGCGCCGGTGTCGCAGCTAAACTGGCAACTGTAACGTCGGCAGCACCTACAAGCAAGCAGGAACTCAAAACACTACTGGCTTCGAAAGGGGAACGCGCCAAACTCCAAGCAGCCAACGACGAGTATAATAACTGGAAACCAGGCGCCAAGCCTGAGGACTTCGACGCCCACATCAAGAAAGTGTTCGGCGCAGAAGACGGCAAAGACAGCGCCTATGCCATTGCACTTGAAGGAATATCCATTGAGGTTCCCCTCGGAGGAGGACAAACACAAAACAAACAACTCTATTCCATGCAGCCAAAAGACCTAATGGCAGCTTTAATAGGAACGATAGCAGAACTCCAAACAGCCGCAGCAACCAAACCAGCATGCCCAGGCCATAAACAAACAACCACGGAAAGTGACGCCCTATGCAGTAAAATAAAGGATGCAAACGAATGCAACAGCAAGCCTTACTGCAGTTATAACGAAACCGCAGCTTATGGCGACAAAAAGTGCCAATTTAATGAAACAAAGGCCTCAAAAAATGGAGTCCCTGTAACGCAAACTCAAACTGTAGAACCTTCAACCAATCCAGAAAAGTGCAAAGGGAAAGAAGAGAAAGACTGCAAATCCCCGAATTGTAAATGGGAGGGCGAAACTTGCAAAGATTCCTCTATTCTAGTAAACAAGAAATTCGCCCTCAGCGTGGTTTCTGCCGCATTTGTGGCCTTGCTTTTTTAATTTTCCCCCTCTTTTTCTTGCTAAAAATTCTTGCTACTTGAAAAATTTTCTGATATATTTTAACAC"
donors = {
    "Tbb1125VSG-228": "CTAAAAACAGAGATGATGTTACGAAAAGCACGCGACAAAATAACACAGTCACGAGAAACAACAGGGCAAAACGCAGCCATGAGAGCTGGCACTTAACAAATTGCGCATCTTATTTGCCAACAAAAGAATTGACTCATATGCTGTGGCATGCTATATAAGAAAAAAATACAATCTAAAATTGTAAAAGTAAAAAAAATGAGAATACAAGCGCGATCATCACCAAACAGCAATCTCAATACTAAATCATAGAAACAGAAGCCAAAGAGGGAGAGCAACTCATTTTCACCCCTAGTGCCAACAATGGTCGCTAAGAAGTGCAGCGCAGCATTAAAGATAGTAATGTTAGTCGGTGCCGCACTGACACTACACCAACAACAAGCTCTAGCTCAGACCGCTGGTAGGCCCCTTGCAGATGCGGTAGGCAAAGCACTCTGCACTTATTCAAAGACAGCCAAACGACAGGCAGCAAACCTAGCCCAAGCTCTAGATCGCGGCATCACAGCAGCAAAAAAGTCGCAACAAGCGCAGCAGTTAGCGACGATAGCACTGGCGAAACTACCCCACTACAGAGAAGCAGCAGCGACGATCCTCATTTACGCCAAAAACAAAAGAGCAGAAGCAGAAGCAAACATCGAAAACTGGAAAGGCCAGAAAACCAAACTGGTGGGGCAGGCAATGTATTCCTCAGGCAGAATCGACGAGCTGATGTTGATGCTAGAAGGCCACAGAGACGGACAATCAGCAGGGCAAACCAAAACTTGCCTAGGCGCAGCAGGAAACGGCAACACAGTAGATGAATTCGTCAAAACAGAGTGCGACACGGAACAAGACCACAACATCAACGCCGACGAATCAGACATAGAACAAGCGGCAGCAACCCTAAGCCAGGAAAATAGAGACCCGGAAGCAGGCGGCGGAACCAACTGCAAGATCACAGGCAACCTTGCCAGCGACTACGACAGTCATCCAAATGATCTGAGTTTGCTAGGCGGACTGCTAACAATACACAATGGGGGCGGCTTTAAGGCAACGACAACAATAAAAACCGCGGCGGCGGGCAACAAACTAATCAGCGCCCTCGCGAGCAAGGTTAACGACATCGCTGCTAACCTCAAAGCACACACGGAATCGGCACCAACGACCAAACAAGAACTCAAGACACTACTGGGCAGCAAAGGAGCACGGAGCAAGCTAGAAGCAGCCAACGACGAGTACAATAGCTGGGAAGCAGGAAAAAAGCCTGTAAACTTCGACGAGCACATCAAAAAAGTGTTCGGCGCGGAAGACGGCAAAGACAGCGCCTATGCCCTTGCACTTGAAGGGATATCCATTGAAGTTCCACAAAAACCAGGGACCACAGAAAGCAAACAACTCTATTCCATGCAGCCAAAAGACCTAATGGCAGCTTTAATAGGAACCATAGCAGAAATACAAAAAGCCGCAGCGACAAAAGCACCATGCCCAAAGCATAAACTGACAAGCGCTGAAAGTGACGCCCTATGCAGTAAAATAAAGGATGCAAACGAATGCAACAGCAAGCCTTTCTGCAGTTATAACAGCACCGAAACTGACACAGCTAAAAAGTGCCAATTTAATGAAACCAAAGCTGACAAAAGTGGAGTTTCGTTGCCTAAAACCGGACCTACCGGTACTGAAGCAACAACTGATAAGTGTAAAGATAAGACAAAAGATGAGTGCAAATCTCCGAATTGTAAATGGGAGGGCGAAACTTGCAAAGATTCCTCTATTCTAGTAAACAAACAATTCGCCCTCAGCATGGTTTCTGCTGCCTTTATCGGTTTGATATCATTTTAGAATTGTAAGGATTTTTATAAATTTTATGAGTTACGAAAACTTATTATTTTGAGAAACTTCTTAATACTTGATATAATTTAATATATTTTAACATTTTTCGGTAGAAATGTGCGAATTAGCGATTATACAAATGTTGGAAAATATAAATAAAATG",
    "Tbb1125VSG-3110": "ACAAGCTCTAGCTCAGACCGCTGGTAGGCCCCTTGCAGATGTGGTAGGCAAAACTCTATGTACTTATTCAAAAACGGCCAAACGCCAGGCAGCAAACCTGGCACAAACACTAGAACGAGCCAGCTCAGCAGCAAAGCAATCCAGACAAGCGCAGCAGTTAGCGGCTTTAGCCCTGGCGAAACTCCCAGAGTACAAAGAAGCAGCCGCGACGCTGTTAATTTACGTCATGATGAAAGTGGAAGCAGCACAAGCAAGCATCGAAAACTGGACAGGAGAGAAGACAAACTAGTAGAGCAGGCGATGTATTCCTCAGGCAGGATAGACGAGCTGATGTTGCTCCTAGAAGGGCACCGGGAGGACGGACCGAGCGGTGCGGACAAAACTTTCCTAGGCGCGGCCGCCGGCGGCAATACAGTAAATGAATTCGTCAAAACAGAATGCGACACGGAACACGACCACAACATCGAGGCAGACAACTCAAACATAGGGCAAGCGGCGACGACTCTAAGCCAAGAAAGTACAGACCCAGAGGCAGCCGGCAGAAGCGACTGCAAGGTCACAACCAACCTTGCTAGCGACTACGACAGCCATGCGAATGAACTACCGCTACTCGGCGGACTGCTAACCATACACAATGGGGGCGGCTTCAAAAGCGGTCAGACCATACAAACTACAGCAACCACGAACAAGCTAATCAGCGCACTCAAAAATAAGGGCGCCGGTGTCGCCGAGAGCCTAAAAACTGTAACAGCGGCAGCACCTACAAACAAACAGGAGTTCAAGACACTACTGGCCTCAAAAGCCGAGCGTGCCAAACTGCAAGCAGCGAACGAAGAGTATAATAACTGGAAACCAGGCGCCAAGCCCGCGGACTTCGATGCCCACATCAAAAAAGTGTTCGGCGCGGAAGACAACAAAGACAGCGCCTATGCCCTTGCACTTGAAGGGATATCCATTGAGGTTCCCCTCGGAGGAGGACAAACACAAAACAAACAACTCTATTCCATGCAGCCAAAAGACCTAATGGCAGCTTTAATAGGAACGATAGCAGAACTCCAAACAGCCGCAGCGACGAAACCAGCATGCCCAGGCCATAAACAAACAACCACTGAAAGTGACGCCCTATGCAGTAAAATAAAGGATGCAAACGAATGCAACAGCAAGCATTTCTGCAGTTATAACGGCACCGAAACTGACTCAGCTAAAAAGTGCAAATTTAATGCCTCAAAAGCTTCAGCAAGTGGTGCCCCTGTAACACAAAGTCAAACCGGAGGGAGTGAAACAACAACAGAGAAATGCAAAGGCAAGAAAAAGGATGACTGCAAATCTCCGGATTGTAAATGGGAAGGCGAAACTTGCAGAGACTCTAGTTTCTCATAAATAAGAAATTTTCTCTGATAGCTGCTGCTTTGTGAATTTGGTGGTATTTTAGAATTTTAATGATTTTTATGCAATTTTATGAAAATTTATGAAAATTTTCTATTTCGAGATAATTTAAAATATTTAAGCACTTTATGTTGGAAATGTGAAAATGAATAAAAATATGGAAATACAAAAAATATGAAATTTTGGTATGATAGTGAACTATGAGTGCAAAATAGTAGGACTACAGGATGTGAAAAAATAGCGCTATTACATAATTTGGTTTATTTTTTTGTTTGATGAATATTAAAAGCGCTT",
    "Tbb1125VSG-2986": "CTAACAACAAAAATGGTGTTACGAAAATTTCGCGACAAAATAACACATTGAAAAGAGACAACAAACCGAAAAAACACCGCTAGAGCTAGCGCTTAACAAATTGCTCATCTTATTTGCCAACAAAAGAATTGACTCATACGCTGTGGCATGCCATAGAAGAAAAAAAATACAATCTATAATTGTAAAAGAAAAAAAATGAGAATAAAAGCGCGATCATCACCAAACCGCAATCTCAATACTAAATCATAGAAACAGAAGCCAAAGAGGGAGAGCCACTCATTTTCACCCCTAATACTGACAATGGTCGCCAAGGAGTGCAACGTAGCATTAAAAATCGTAATGCTAGTCGCTTCAGCACTGACACTACACACACAACAAGCTCTAGCTCAGACAGCTGGTAGGCCCCTTGCAGATGTGGTCGGCAAAGCTCTATGTACTTATTCAAAAACGGCGAAACGACAGCCAGCGAATCTAGCCCAAGCTCTAGATCGCGCCATCACAGCAGCAAAGAAATCGGAGCAAGCACAGGCGTTAGCAGCCGTTGCCCTGGCCAAGCTCCCAGACTATCAGCAAGAAGCCGGAACGCTGTTAATTTACGTCAGGATGAAAGTGGAAGCAGCACAAGCGAGCATCGAAAACTGGACAGGAGAAAAGACAAAACTGGTAGAGCAGGCGATGTATTCCTCAGGCGGGATAGACGAGCTGATGTTGCTCCTAGAAGGGCACCGGGAGGACCGGGCGAACGGCGCCGACAAAACCTGCCTAGGCGCAGCAACAAGCGGAAACACAGTCGCTGAATTCGTCAAAAGAAATTGCGATACGGAAAATGATCACGACATCAGCGCGGACAACTCAGACATAGGCCAAGCGGCGGCAGATCTAAGCCAAGCAAGCACAGACACAGAGGCAGGCGGCGGAAGCAACTGCAAAATAACAGCAAACCTTGCCAGCGACTACGACAGTCATGCGAATGAACTAACGCTACTCGGCGGGCTGCTAATCATACACAATGAAGGTGGCTTTAAAAGCGGTCAAACCATAAAAACCGCAGCAACCGCGAACAAGCTAATCAGCGCCCTCAAAAATAAAGGAACCAGCGTTGCCAAGAGCCTAAAAACAGTAACAGCGGCAGCACCTACAAACAAACAGGAGTTCAAGACACTACTGGCTTCGAAAGGGGAGCGTGCAAAACTCCAAGCAGCCAACGACGAGTATAATAACTGGAAACCAGGCGCCAAGCCTGTGGACTTCGATGCCCACATCAAGAAAGTGTTCGGCGCAGAAGACGGAAAAGACAGCGCCTATGCCATTGCACTTGAAGGGATATCCATTGAGGTTCCCCACGGAGCAAGGAAAACAGAAAGCAAACAACTTTATTCCATGCAGCCAAAAGGCCTAATGGCAGCTTAAATAGGAACCATAGCAGAACTTCAAACAGCCGCAGCGACGAACACAGTTTGGCCAAAACATAAACAAACAACCACTGAAAGTGACGCTTTATGCAGTAAAATTAAGGACGCAAACAAATGCAGCAGCAAGCCTTTCTGCAGTTATAACGGCACAGAAACTGAATCAGCTAAAAAATGCAAATTTAATGCGACAAAAGCTGAAAACTCCGGCGCTTCTGTAACACAAAGTCAAACCGGAGGGAGTGAAACAACAACAGAGAAATGCAAAGGCAAGAAAAAGCAGGAGGACTGCAAATCTCCG",
    "Tbb1125VSG-7358": "GCGGCTCTACCGCTACTCGGCGGACTGCTAACCATACACAATGGGGGCGGCTTCAAAAACGGCCAGACCATACAAACCACAGCAACCACGAACAAGCTAATCAGCGCACTTAAAAATAAAGGAGCCGGTGTCGCCGAGAGCCTAAAAACTGTAACATCGGCAGCACCTACAAACAAGCAGGAGCTCAAGACACTACTGGCTTCAAAAGGGTAGCGTACCAAACTCCAAGCAGCCAACGACGAGTATAATAACTGGAAACCAGGCGCCAACCTTGAGGACTTCGATGCCCACATCAAGAAAGTGTTCGGCGCAGAAGACAGCAAAGACAGCGCCTATGCCATTGCACGTGAAGGGATATACATTAAAGTTCCAACTAAAGCAGGGAAAACAGAAAGCAGACAACTCTATTCCATGCAGCCAAAAGACTTAATGACAGCTTTAATAGGAACCATAGCAGAACTCCAAACAGCCGCAGCGACGAAACCAACATGCCCAGACCATAAACGGGCAACCACTGAAAGTGACGCCCAATGCAGTAAAATAAAGGATGAAAACGAATGCAACAGCAAGCATTTCTGCAGTTATAACGGCACCGAAACTGACTCAACTAAAAAATGCAAATTTGATGCCAAAAAAGCCACATCAAATAGTGTCTCTGTAACACAAACTCAAACTGGAGGACAGAAACTGCAACAGGAAATCGCAAAGGGAAAGAACAAAAAGACTGCAAATCTGCGGATTGTAAATGGGAGAGAACAGATTGCAAAGATTTCAGCATTCTCGTCAATAAGAAATTGGCTCTGAGTATGGCTGCTGCTTTTGTTAGTTTTGCGGCAATTTAAAATTCTATAATTTTAAGGATATTTGCTCAATTTTGCAATATTTATGAAATTTCTTGTTTTGGGAGAATTTGCTAACATATGATCTATTTTAACAACTTTTTGTCGGATATGTGAAAATAAGTAAAAATATGGGAATACGAAAAATATGAAATTTTGGTATAATAGAGGACTATTGGTGCAAAATAGTGGGGGTCAACGTATGGAAAATCAACTATAATATAATTTGGCTTATTTTGTTTGTTTGATGAATATTAAAAGCGCT",
    "Tbb1125VSG-4156": "GCCTGCCAACAAAAATGGTGTTACGAAAATTGCGCGACAAAATAACACATGGACGACAGACAACAGGCCAAGACAAAGCCATTAGAACTGGCACTTAACAAATTGCGCATCTTATTTGCCAACAAAAGAATTGACTCATACGCTGTGGCATGCTATAGAGGAAAAAAATACAGTCTATAATTGTAAAAGTAAAAAATGAGAATACAAGCGCGCTCATCACCAAACCGCAATCTCAATACTAAATCATAGAAACAGAAGCCAAAGAGGGAGAGCCACTCATTTCCACCCCTAATACTGGCAATGGTCACCAAGGAGCGAAACGCAGCATTAAAAATTGTAATGTTAGTCGCTTCAGCACTGACACTACACCCACAACAAGCTCTAGCTCAGACCGCTGGTAGGCCCCTTGCAGATGTGGTAGGCAAAACTCTATGTACTTATTCAAAAACGGCCAAACGCCAGGCAGCAAACCTGGCGCAAACACTACAACGAGCCAGCTCAGCAGCAAAGCAATCCAGACAAGCGCAGCAGTTAGCGGCTTTAGCACTGGCCAAACTGCCAGACTACAAAGAAGCAGCCGCGACACTGTTAATTTACGCCACGCACAAAATACAAGACGCGCAAGCCAGCATCGAAAACTGGACAGGAGAGAATACTAAGCTAGTTGGCCAGGCGATGTATTCCTCAGGGAGAATCGACGAACTGATGTTGCTACTAGAAGGGCACCGAGAGGACGGCGCGAACGGACAGGACAAAACTTGCCTAGGCGCGGCCGCCGGCGGCAATACAGTAAATGAATTCGTCAAAACAGAATGCGACACGGAAAGCGGCCACAACATCGAGGCAGACAACTCAAACATAGGGCAAGCGGCAACGACTCTAAGCCAAGAAAGTACAGACCCAGAAGCCAGCGGAGGCGCAAGCTGCAAAATAACAGCAAACCTTGCCACTGACTACGACAGCCATGCGAATGAGTTACCGCTACTCGGCGGCCTGCTAACCATACACAACGCAGGCGGCTTCAAAACAGGACAAAGCTTGCAAACCGCAGCACCAACCAACAAGCTAATCAGCGCACTCAAAAATAAGGGCGCCGGTGTCGCAGCTAAACTGGCAACTGTAACGTCGGCAGCACCTACAAGCAAGCAGGAACTCAAAACACTACTGGCTTCGAAAGGGGAACGCGCCAAACTCCAAGCAGCCAACGACGAGTATAATAACTGGAAACCAGGCGCCAAGCCTGAGGACTTCGACGCCCACATCAAGAAAGTGTTCGGCGCAGAAGACGGCAAAGACAGCGCCTATGCCATTGCACTTGAAGGAATATCCATTGAGGTTCCCCTCGGAGGAGGACAAACACAAAACAAACAACTCTATTCCATGCAGCCAAAAGACCTAATGGCAGCTTTAATAGGAACGATAGCAGAACTCCAAACAGCCGCAGCAACCAAACCAGCATGCCCAGGCCATAAACAAACAACCACGGAAAGTGACGCCCTATGCAGTAAAATAAAGGATGCAAACGAATGCAACAGCAAGCATTTCTGCAGTTATAACGGCACCGAAACTGACTCAGCTAAAAAGTGCAAATTTAATGCAACAAAAGCTTCAGCAAGTGATGCCCCTGTAACACAAGGTCAAACTGGAGGGAGTGAAACAACAACATGGAATTTCAAGAGGAAACTACAAGAAGAATGCACCAAGGCTCCAGAATGCAAATGGGAAAATAACGCTTTCAAAGATTCCATTTTTATGGTCAATAATAAATTGGCTCCAGTTGTTTATGGCTTTACGAGTTTTGTGGTATTTTCAAAATTATAGTGAATTTTTTTGCTTAATTTTATAAAATTTATAAAATATTTTATAACTTGATATATTTCACTTTTTGATGAAAATTTACAAATTAGTAAAAACTTTGAGAATTTGAAAAATCTGAAATTAAAAAAAATATGTTAGACTTAGAACTGCGGATGCAAATTTGTAGAGTCACAGGGTATTAAAAATGAGTGCTAATATTTTTTGACTTATTTTTCTGATTTTATGAATATTAGTTAGGGTTGTAATAATAGTGAGAATAATGATAGGAGAATGTTGTGAGAGTGTATATACGAAAATTATAAT"
}
donors["Tbb1125VSG-228"] = donors["Tbb1125VSG-228"][214:]
donors["Tbb1125VSG-2986"] = donors["Tbb1125VSG-2986"][214:]
donors["Tbb1125VSG-4156"] = donors["Tbb1125VSG-4156"][214:]
donor_starts = {
    "Tbb1125VSG-228": 0,
    "Tbb1125VSG-3110": 160,
    "Tbb1125VSG-2986": 0,
    "Tbb1125VSG-7358": 755,
    "Tbb1125VSG-4156": 0
}
guides = {
    "G_141": "TTCAAAAACGGCCAAACGCC",
    "G_300R": "GGCGTAAATTAACAGTGTCG",
    "G_592": "AGTACAGACCCAGAAGCCAG",
    "G_792": "CGCCGGTGTCGCAGCTAAAC",
    "G_909R": "GTCGTTGGCTGCTTGGAGTT",
    "G_1357": "ACCAATCCAGAAAAGTGCAA"
}
with open("guide_stats.csv", "w") as output, open("guide_fastas_guide_seq.fa", "w") as fastas:
    for guide in guides:
        if len(antat_seq.split(guides[guide])) == 2:
            upstream_len = len(antat_seq.split(guides[guide])[0])
            downstream_len = len(antat_seq.split(guides[guide])[1])
            upstream_position = upstream_len + 17
            downstream_position = downstream_len + 3
            reverse = False
            pam = antat_seq.split(guides[guide])[1][:3]
            cut_site = upstream_len + 17

        else:
            new_rev_guide = rev_complement(guides[guide])
            guides[guide] = new_rev_guide
            upstream_len = len(antat_seq.split(new_rev_guide)[0])
            downstream_len = len(antat_seq.split(new_rev_guide)[1])
            reverse = True
            pam = antat_seq.split(guides[guide])[0][-3:]
            cut_site = upstream_len + 3
            #other_seq = (cut_site - 250, cut_site + 250)

        #other_seq = (cut_site - 250, cut_site + 250)
        start = cut_site - 250
        if start < 0:
            start = 0
        end = cut_site + 250
        antat_seq_500bp = antat_seq[start:end]
        for donor in donors:
            if donor_starts[donor] > cut_site:
                continue
            if donor_starts[donor] != 0:
                antat_temp_seq = antat_seq[donor_starts[donor]:]
                vsg_start = start - donor_starts[donor]
                vsg_end = end - donor_starts[donor]
                upstream = upstream_len - donor_starts[donor]
                #downstream = donor_starts[donor]
                #antat_seq_match_donor = antat_seq[donor_starts[donor]:end]
            else:
                antat_temp_seq = antat_seq
                vsg_start = start
                vsg_end = end
                upstream = upstream_len
            if vsg_start < 0:
                vsg_start = 0
            if vsg_end > len(antat_temp_seq):
                vsg_end = len(antat_temp_seq)
            antat_seq_match_donor = antat_temp_seq[vsg_start:vsg_end]
                #antat_seq_match_donor = antat_seq_500bp
            # if guide == "G_141" and donor_starts[donor] < start:
            #     vsg_start = donor_starts[donor]
            # else:
            #     vsg_start = start
            if reverse:
                pam_donor = donors[donor][upstream - 3: upstream]
            else:
                pam_donor = donors[donor][upstream + 20: upstream + 23]
            guide_donor = donors[donor][upstream:upstream + 20]
            seq_donor = donors[donor][vsg_start:vsg_end]
            if len(antat_seq_match_donor) != len(seq_donor):
                antat_seq_match_donor = antat_seq_match_donor[0:len(seq_donor)]

                pass
                # if donor == "Tbb1125VSG-7358" and guide == "G_792":
                #     dis_seq = hamming(list(antat_seq_500bp[40:]), list(seq_donor)) * len(seq_donor)
                # elif donor == "Tbb1125VSG-7358" and guide == "G_909R":
                #     dis_seq = hamming(list(antat_seq_500bp[124:]), list(seq_donor)) * len(seq_donor)
            # dis_seq = hamming(list(antat_seq_match_donor), list(seq_donor)) * len(antat_seq_match_donor)
            dis_seq = lev.distance(antat_seq_match_donor, seq_donor)
            dis_pam = hamming(list(pam), list(pam_donor)) * len(pam)
            dis_guide = hamming(list(guides[guide]), list(guide_donor)) * len(guides[guide])
            # dis_seq = hamming(list(antat_seq_500bp), list(seq_donor)) * len(antat_seq_500bp)
            output.write(", ".join([guide, donor, str(dis_pam), str(dis_guide), str(round(dis_seq)), pam_donor,
                                    guide_donor, seq_donor]) + "\n")
            fastas.write("> " + guide + "_" + donor + "\n")
            fastas.write(guide_donor + "\n")


# use split to find and if not, rev complement then find.
# then get the PAM sequence.
# then get 250 up + down of cut site, 6 away from pam spot
# identify coordinates of sequence, then cooresponding sequence in all donor VSGs
# get hamming distance for each guide/pam/500bp sequence
# get number of recombination sites for each 500bps up/downstream